---
title: Turtle tracker
hero_image: images/banner.png
description: Draw the routes taken by real sea turtles during their nesting time at
  the islands of Príncipe and Poilão off the west coast of Africa
version: 1
listed: true
copyedit: false
last_tested: '2020-09-10'
steps:
- title: Introduction
- title: Using coordinates
- title: Draw the route
  completion:
  - engaged
- title: Lists of coordinates
- title: Real turtle movements
- title: Import data from a file
  completion:
  - internal
  completion:
  - external